CREATE TABLE `USERS`(
	`ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`USER` VARCHAR(32),
	`MAIL` VARCHAR(32),
	`PASSWORD` VARCHAR(64),
	`TYPE` INT(11),
	UNIQUE (`USER`,`MAIL`),
	CHECK (TYPE BETWEEN 0 AND 1)
);

CREATE TABLE `CATEGORIES`(
	`ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`PARENTID` INT(11),
	`TITLE` VARCHAR(32) UNIQUE
);

CREATE TABLE `ARTICLES`(
	`ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`TITLE` VARCHAR(96) UNIQUE,
	`TYPE` INT(11),
	`CATEGORIES` INT(11),
	`DATE` DATE,
	`CONTENT`	TEXT,
	`IMAGEHEADER` TEXT,
	CHECK (TYPE BETWEEN 0 AND 2)
);

INSERT INTO `USERS` (`ID`,`USER`,`MAIL`,`PASSWORD`, `TYPE`)
VALUES ('','Admin','example@mail.com','21232f297a57a5a743894a0e4a801fc3','0');
